"""empty message

Revision ID: 1ed3e9b1e66e
Revises: 86e5d6137a78
Create Date: 2022-04-07 14:46:44.096867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed3e9b1e66e'
down_revision = '86e5d6137a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('good_type', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=24), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('channel_type', sa.String(length=32), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('is_launched', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
    sa.ForeignKeyConstraint(['good_type'], ['course_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('order', sa.String(length=32), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('goods', sa.Integer(), nullable=True),
    sa.Column('trade_no', sa.String(length=32), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('pay_method', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('pay', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['goods'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('order')
    )
    op.add_column('vip', sa.Column('price', sa.DECIMAL(precision=20, scale=2), nullable=True))
    op.add_column('vip', sa.Column('exempt_cour', sa.Integer(), nullable=True))
    op.add_column('vip', sa.Column('vip_cour', sa.Integer(), nullable=True))
    op.add_column('vip', sa.Column('environment', sa.Integer(), nullable=True))
    op.add_column('vip', sa.Column('save', sa.Integer(), nullable=True))
    op.add_column('vip', sa.Column('client', sa.Integer(), nullable=True))
    op.add_column('vip', sa.Column('ssh', sa.Integer(), nullable=True))
    op.add_column('vip', sa.Column('web_ide', sa.Integer(), nullable=True))
    op.add_column('vip', sa.Column('discounts', sa.Integer(), nullable=True))
    op.add_column('vip', sa.Column('exempt_study', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vip', 'exempt_study')
    op.drop_column('vip', 'discounts')
    op.drop_column('vip', 'web_ide')
    op.drop_column('vip', 'ssh')
    op.drop_column('vip', 'client')
    op.drop_column('vip', 'save')
    op.drop_column('vip', 'environment')
    op.drop_column('vip', 'vip_cour')
    op.drop_column('vip', 'exempt_cour')
    op.drop_column('vip', 'price')
    op.drop_table('orders')
    op.drop_table('user_course')
    op.drop_table('goods')
    # ### end Alembic commands ###
