"""empty message

Revision ID: 220c9ebb8139
Revises: 1794fbf2c6eb
Create Date: 2022-04-06 15:20:41.212058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '220c9ebb8139'
down_revision = '1794fbf2c6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('question_type')
    op.add_column('comment', sa.Column('cid', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('sid', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('top', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('excellent', sa.Integer(), nullable=True))
    op.drop_column('comment', 'q_id')
    op.drop_column('comment', 'favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('favorite', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('q_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('comment', 'excellent')
    op.drop_column('comment', 'top')
    op.drop_column('comment', 'sid')
    op.drop_column('comment', 'cid')
    op.create_table('question_type',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('question',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('top', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('excellent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('examine', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('favorite', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('is_delete', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
