"""empty message

Revision ID: 22667fa75bae
Revises: 220c9ebb8139
Create Date: 2022-04-06 18:25:41.225595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22667fa75bae'
down_revision = '220c9ebb8139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning')
    # ### end Alembic commands ###
