"""empty message

Revision ID: 2cedc15bb8d6
Revises: 
Create Date: 2022-04-09 17:57:01.918783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cedc15bb8d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('reply', sa.Integer(), nullable=True),
    sa.Column('top', sa.Integer(), nullable=True),
    sa.Column('excellent', sa.Integer(), nullable=True),
    sa.Column('favorite', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('img', sa.String(length=888), nullable=True),
    sa.Column('desc', sa.String(length=100), nullable=True),
    sa.Column('section_sum', sa.Integer(), nullable=True),
    sa.Column('add_sum', sa.Integer(), nullable=True),
    sa.Column('study_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('desc', sa.String(length=64), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('exempt_cour', sa.Integer(), nullable=True),
    sa.Column('vip_cour', sa.Integer(), nullable=True),
    sa.Column('environment', sa.Integer(), nullable=True),
    sa.Column('save', sa.Integer(), nullable=True),
    sa.Column('client', sa.Integer(), nullable=True),
    sa.Column('ssh', sa.Integer(), nullable=True),
    sa.Column('web_ide', sa.Integer(), nullable=True),
    sa.Column('discounts', sa.Integer(), nullable=True),
    sa.Column('exempt_study', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('stage_name', sa.String(length=64), nullable=True),
    sa.Column('path', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['path'], ['path.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('img', sa.String(length=500), nullable=True),
    sa.Column('nick_name', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('is_superuser', sa.Integer(), nullable=True),
    sa.Column('vip', sa.Integer(), nullable=True),
    sa.Column('vip_expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vip'], ['vip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unid', sa.String(length=64), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('auth_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=24), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.Column('img_path', sa.String(length=888), nullable=True),
    sa.Column('video', sa.String(length=888), nullable=True),
    sa.Column('course_type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('learner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_type'], ['course_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_stage',
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
    sa.ForeignKeyConstraint(['stage'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('course', 'stage')
    )
    op.create_table('course_tag',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['course.id'], ),
    sa.ForeignKeyConstraint(['tid'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('cid', 'tid')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('good_type', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=24), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('channel_type', sa.String(length=32), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('is_launched', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
    sa.ForeignKeyConstraint(['good_type'], ['course_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('video', sa.String(length=888), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('order', sa.String(length=32), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('goods', sa.Integer(), nullable=True),
    sa.Column('trade_no', sa.String(length=32), nullable=True),
    sa.Column('pay_time', sa.DateTime(), nullable=True),
    sa.Column('pay_method', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('pay', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('record', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['goods'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('order')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('user_course')
    op.drop_table('section')
    op.drop_table('goods')
    op.drop_table('course_tag')
    op.drop_table('course_stage')
    op.drop_table('course')
    op.drop_table('auth')
    op.drop_table('user')
    op.drop_table('stage')
    op.drop_table('vip')
    op.drop_table('tag')
    op.drop_table('path')
    op.drop_table('learning')
    op.drop_table('course_type')
    op.drop_table('comment')
    # ### end Alembic commands ###
