"""empty message

Revision ID: 518f5bc7b97e
Revises: 
Create Date: 2022-04-03 16:38:31.911147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518f5bc7b97e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=64), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('img', sa.String(length=500), nullable=True),
    sa.Column('nick_name', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('is_superuser', sa.Integer(), nullable=True),
    sa.Column('vip', sa.Integer(), nullable=True),
    sa.Column('vip_expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vip'], ['vip.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unid', sa.String(length=64), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('auth_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=24), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=256), nullable=True),
    sa.Column('img_path', sa.String(length=888), nullable=True),
    sa.Column('video', sa.String(length=888), nullable=True),
    sa.Column('course_type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('follower', sa.Integer(), nullable=True),
    sa.Column('learner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_type'], ['course_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_tag',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['course.id'], ),
    sa.ForeignKeyConstraint(['tid'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('cid', 'tid')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('video', sa.String(length=888), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('section')
    op.drop_table('course_tag')
    op.drop_table('course')
    op.drop_table('auth')
    op.drop_table('user')
    op.drop_table('vip')
    op.drop_table('tag')
    op.drop_table('course_type')
    # ### end Alembic commands ###
