"""empty message

Revision ID: 86e5d6137a78
Revises: 22667fa75bae
Create Date: 2022-04-07 09:08:19.730703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e5d6137a78'
down_revision = '22667fa75bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('favorite', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'favorite')
    # ### end Alembic commands ###
