"""empty message

Revision ID: a285f2effa7e
Revises: b755247a47ba
Create Date: 2022-03-29 18:10:42.533757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a285f2effa7e'
down_revision = 'b755247a47ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otherUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('auth_type', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('otheruser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otheruser',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('auth_type', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.uid'], name='otheruser_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('otherUser')
    # ### end Alembic commands ###
